# Generated by Django 4.2.1 on 2023-06-01 16:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('account', '0002_remove_user_is_petowner_remove_user_is_veterinary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.CharField(blank=True, max_length=100, null=True, verbose_name='SSN')),
                ('profilePicture', models.ImageField(blank=True, null=True, upload_to='images/profile/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Image')),
                ('phone1', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone 1')),
                ('phone2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone 2')),
                ('specialization', models.CharField(blank=True, max_length=100, null=True, verbose_name='Specializations')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('dob', models.DateField(verbose_name='Birthdate')),
                ('locationAddress', models.CharField(max_length=200, verbose_name='Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainers', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', models.CharField(max_length=20, unique=True, verbose_name='National ID OR Passport')),
                ('git_account', models.CharField(max_length=1000, unique=True, verbose_name='Git Account Link')),
                ('profilePicture', models.ImageField(blank=True, null=True, upload_to='images/profile/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Image')),
                ('phone1', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone 1')),
                ('phone2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone 2')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('dob', models.DateField(verbose_name='Birthdate')),
                ('locationAddress', models.CharField(max_length=200, verbose_name='Address')),
                ('status', models.CharField(choices=[('', 'Select Status'), ('Pending', 'Pending'), ('Awarded', 'Awarded')], default='', max_length=10, verbose_name='Status')),
                ('cohort', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='main.cohort', verbose_name='Cohort belonging')),
                ('stack', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stacks', to='main.stack', verbose_name='Stack belonging')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainees', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.CharField(blank=True, max_length=100, null=True, verbose_name='SSN')),
                ('profilePicture', models.ImageField(blank=True, null=True, upload_to='images/profile/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Image')),
                ('phone1', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone 1')),
                ('phone2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone 2')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('dob', models.DateField(verbose_name='Birthdate')),
                ('locationAddress', models.CharField(max_length=200, verbose_name='Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Company Name')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('fixed_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone Number')),
                ('location', models.CharField(max_length=200, verbose_name='Location Address')),
                ('logoFile', models.ImageField(blank=True, null=True, upload_to='images/profile/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Logo Image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
