# Generated by Django 4.2.1 on 2023-06-02 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_trainer_trainee_programmanager_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmanager',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='programmanager',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='dob',
        ),
    ]
