# Generated by Django 4.2.1 on 2023-06-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_trainee_nid_alter_trainee_cohort_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='git_account',
            field=models.URLField(max_length=1000, unique=True, verbose_name='Git Account Link'),
        ),
    ]
