# Generated by Django 4.2.1 on 2023-06-07 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_cohort_schedule_schedule_name'),
        ('account', '0006_alter_trainee_git_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainees', to='main.cohort', verbose_name='Cohort belonging'),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainees', to='main.stack', verbose_name='Stack belonging'),
        ),
    ]
