# Generated by Django 4.2.1 on 2023-06-07 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_trainee_git_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='cv_document',
            field=models.FileField(blank=True, null=True, upload_to='document/applicants/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc'])], verbose_name='CV Document'),
        ),
    ]
