# Generated by Django 4.2.1 on 2023-06-07 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_trainee_cv_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='cv_document',
            field=models.FileField(blank=True, null=True, upload_to='document/trainees/cv/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc'])], verbose_name='CV Document'),
        ),
    ]
