# Generated by Django 4.2.1 on 2023-06-07 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_cohort_schedule_schedule_name'),
        ('account', '0010_alter_trainee_cv_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='stack',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='trainers', to='main.stack', verbose_name='Stack belonging'),
        ),
    ]
