# Generated by Django 4.2.1 on 2023-06-09 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_assignment_alter_cohort_schedule_cohort_group_and_more'),
        ('account', '0011_trainer_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='trainees', to='main.group', verbose_name='Group belonging'),
        ),
    ]
