# Generated by Django 4.2.2 on 2023-06-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_trainee_company_deployed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainee',
            old_name='company_deployed',
            new_name='companyDeployed',
        ),
        migrations.AddField(
            model_name='trainee',
            name='deployedDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='When Deployed'),
        ),
    ]
