# Generated by Django 4.2.2 on 2023-06-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_trainee_deployeddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Awarded', 'Awarded')], default='Pending', max_length=10, verbose_name='Status'),
        ),
    ]
