# Generated by Django 4.2.1 on 2023-06-06 10:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('gender', models.CharField(choices=[('', 'Select Gender'), ('Male', 'Male'), ('Female', 'Female')], default='', max_length=10, verbose_name='Gender')),
                ('phone1', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone 1')),
                ('phone2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone 2')),
                ('locationAddress', models.CharField(max_length=200, verbose_name='Address')),
                ('githubLink', models.CharField(max_length=255)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='document/applicants/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc'])], verbose_name='CV Document')),
                ('status', models.CharField(choices=[('', 'Select Status'), ('Pending', 'Pending'), ('Awarded', 'Awarded'), ('Rejected', 'Rejected')], default='', max_length=10, verbose_name='Status')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('cohort', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='applicants', to='main.cohort', verbose_name='Cohort to Join')),
                ('stack', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='applicants', to='main.stack', verbose_name='Stack to Join')),
            ],
        ),
    ]
