# Generated by Django 4.2.1 on 2023-06-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='educationLevel',
            field=models.CharField(choices=[('', 'Select Education Level'), ('Bachelors Degree', 'Bachelors Degree'), ('Advanced diploma', 'Advanced diploma'), ('High School', 'High School')], default='', max_length=30, verbose_name='Education Level'),
        ),
        migrations.AddField(
            model_name='application',
            name='more',
            field=models.TextField(blank=True, verbose_name='More Information'),
        ),
    ]
