# Generated by Django 4.2.1 on 2023-06-06 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_module'),
        ('recruitment', '0002_application_educationlevel_application_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicants', to='main.cohort', verbose_name='Cohort to Join'),
        ),
        migrations.AlterField(
            model_name='application',
            name='stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicants', to='main.stack', verbose_name='Stack to Join'),
        ),
    ]
