# Generated by Django 4.2.1 on 2023-06-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_alter_application_cohort_alter_application_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='githubLink',
            field=models.URLField(max_length=255),
        ),
    ]
