# Generated by Django 4.2.1 on 2023-06-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cohort_status_cohort_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort_schedule',
            name='schedule_name',
            field=models.CharField(choices=[('', 'Select Schedule'), ('Application', 'Application'), ('Interview', 'Interview'), ('Graduation', 'Graduation')], default='', max_length=12, verbose_name='Status'),
        ),
    ]
