# Generated by Django 4.2.1 on 2023-06-07 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_cohort_schedule_schedule_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Module Name'),
        ),
        migrations.AlterField(
            model_name='module',
            name='stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='main.stack', verbose_name='Stack belonging'),
        ),
    ]
