# Generated by Django 4.2.1 on 2023-06-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_assignment_alter_cohort_schedule_cohort_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='dueDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
