# Generated by Django 4.2.1 on 2023-06-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_assignment_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='createdDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
