# Generated by Django 4.2.1 on 2023-06-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_assignment_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Assignment Title'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=100, verbose_name='Group Name'),
        ),
    ]
