# Generated by Django 4.2.1 on 2023-06-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_assignment_title_alter_group_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Is Marked'),
        ),
    ]
