# Generated by Django 4.2.1 on 2023-06-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_assignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='startDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
