# Generated by Django 4.2.1 on 2023-06-10 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_assignment_startdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
