# Generated by Django 4.2.1 on 2023-06-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Is Completed'),
        ),
    ]
