# Generated by Django 4.2.1 on 2023-06-11 23:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_assignment_documentfiles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='documentFiles',
            field=models.FileField(blank=True, null=True, upload_to='document/course/assignment', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'ppt'])], verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='assignmentreport',
            name='documentFiles',
            field=models.FileField(blank=True, null=True, upload_to='document/course/assignment/report', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'ppt'])], verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='module',
            name='documentFiles',
            field=models.FileField(blank=True, null=True, upload_to='document/course', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'ppt'])], verbose_name='Document'),
        ),
    ]
