# Generated by Django 4.2.2 on 2023-06-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort_schedule',
            name='schedule_name',
            field=models.CharField(choices=[('', 'Select Schedule'), ('Application', 'Application'), ('Interview', 'Interview'), ('Graduation', 'Graduation')], default='', max_length=12, verbose_name='Schedule Name'),
        ),
    ]
